name: Loan_prediction

channels: 
  - defaults

dependencies:
  - python=3.10.14
  - pip<=24.2
  - pip:
    - mlflow==2.15.1
    - cloudpickle==3.0.0
    - numpy==1.26.4
    - scikit-learn==1.5.1
    - scipy==1.14.0